package com.torquelab.autoservice.auth.presentation

enum class AuthUiError {
    EMAIL_REQUIRED,
    PASSWORD_REQUIRED,
    WORKSHOP_NAME_REQUIRED,
    PASSWORD_TOO_SHORT,
    PASSWORDS_DO_NOT_MATCH,
    INVALID_CREDENTIALS,
    AUTHENTICATION_FAILED,
    REGISTRATION_FAILED,
    CONNECTION_ERROR,
    UNEXPECTED_ERROR
}